use_frameworks!

platform :ios, '9.0'

target 'ShippedShield_Example' do
  pod 'ShippedShield', :path => '../'

  target 'ShippedShield_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
