# .slather.yml

coverage_service: coveralls
workspace: ./Example/ShippedShield.xcworkspace
xcodeproj: ./Example/ShippedShield.xcodeproj
scheme: ShippedShield-Example
source_directory: ShippedShield/Classes
binary_basename: ShippedShield
coverage_access_token: szNmq5dv7GDEGh4jxhicFm0f6RrLcTKjz