name: Test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check files
        run: ls -n /Applications/ | grep Xcode*

      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_13.0.app/Contents/Developer

      - name: Test
        run: xcodebuild test -workspace ./Example/ShippedShield.xcworkspace -scheme ShippedShield-Example -enableCodeCoverage YES -destination 'platform=iOS Simulator,OS=15.5,name=iPhone 12'

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --without=documentation --jobs 4 --retry 3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch

      - name: Upload code coverage report
        run: bundle exec slather
        env:
          GIT_BRANCH: ${{ steps.get_branch.outputs.branch }}
          CI_PULL_REQUEST: ${{ github.event.number }}
          COVERAGE_ACCESS_TOKEN: ${{ secrets.COVERAGE_ACCESS_TOKEN }}